// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fx
Rcpp::List fx(const arma::mat& EM, const arma::cube& TM);
RcppExport SEXP _polyqtlR_fx(SEXP EMSEXP, SEXP TMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type EM(EMSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type TM(TMSEXP);
    rcpp_result_gen = Rcpp::wrap(fx(EM, TM));
    return rcpp_result_gen;
END_RCPP
}
// bx
Rcpp::NumericMatrix bx(const arma::vec& s, const arma::mat& EM, const arma::cube& TM);
RcppExport SEXP _polyqtlR_bx(SEXP sSEXP, SEXP EMSEXP, SEXP TMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type EM(EMSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type TM(TMSEXP);
    rcpp_result_gen = Rcpp::wrap(bx(s, EM, TM));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_polyqtlR_fx", (DL_FUNC) &_polyqtlR_fx, 2},
    {"_polyqtlR_bx", (DL_FUNC) &_polyqtlR_bx, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_polyqtlR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
